name: Test

on:
  push:
    branches:
      - main

jobs:
  Firefox:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - run: yarn install

      - run: yarn build

      - run: yarn test --browser firefox
